name: $name
version: $version
main: dev.worldsw.archKing.ArchKingPlugin
description: $description
author: devworld
api-version: "$apiVersion"

permissions :
  akitem.get:
    description: "This is a permission to get arch king item"
    default: op
  akgravity.set:
    description: "This is a permission to change gravity"
    default: op

commands:
  akitem:
    description: "Get arch king item"
    usage: "/akitem <item> <quantity>"
    permission: akitem.get
    permission-message: "You do not have permission to use this command"
  akgravity:
    description: "Toggle gravity"
    usage: "/akgravity (wood,concrete)"
    permission: akgravity.set
    permission-message: "You do not have permission to use this command"

bootstrapper: dev.worldsw.archKing.ArchKingBootstrap
loader: dev.worldsw.archKing.ArchKingLoader